name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Quality checks job
  quality:
    runs-on: ubuntu-latest
    name: Code Quality & Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:run
        # Note: test:run now uses CI-specific config for reliable jsdom unit tests
        # Local browser testing available via: npm run test:browser

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Build project
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
